using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
namespace sync_server
{
    class SettingsManager
    {


        static public void CreateSetting(String port, String folder, String maxV)
        {
            XmlWriterSettings settings = new XmlWriterSettings();
            settings.Indent = true;

            XmlWriter writer = XmlWriter.Create("Setting.xml", settings);
            writer.WriteStartDocument();
            writer.WriteComment("This file is generated by the program.");
            writer.WriteStartElement("Setting");
            writer.WriteAttributeString("Port", port);
            writer.WriteAttributeString("Folder", folder);
            writer.WriteAttributeString("NVersion", maxV);
            writer.WriteEndElement();
            writer.WriteEndDocument();
            writer.Flush();
            writer.Close();

        }

       static  public String[] GetSetting()
        {
            String[] setting= new String[3];
            XmlReader reader = XmlReader.Create("Setting.xml");

            setting[0] = "55555"; 
            setting[1] = "Select Folder";
            setting[2] = "5";
            while (reader.Read())
            {
                if (reader.NodeType == XmlNodeType.Element && reader.Name == "Setting")
                {
                    setting[0] = reader.GetAttribute(0);
                    setting[1]= reader.GetAttribute(1);
                    setting[2] = reader.GetAttribute(2);
                }
            }
            return setting;

        }
    }
}