using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
namespace sync_server
{
    class SettingsManager
    {

		public SettingsManager()
		{
			if (!File.Exists("settings.xml"))
			{
				// Write default settings
				XmlWriterSettings settings = new XmlWriterSettings();
				settings.Indent = true;
				XmlWriter writer = XmlWriter.Create("settings.xml", settings);
				writer.WriteStartDocument();
				writer.WriteComment("This file is generated by the program.");
				writer.WriteStartElement("Setting");
				writer.WriteAttributeString("Port", "55555");
				writer.WriteAttributeString("Folder", "");
				writer.WriteAttributeString("NVersion", "10");
				writer.WriteEndElement();
				writer.WriteEndDocument();
				writer.Flush();
				writer.Close();
			}
		}

        public void writeSettings(String port, String folder, String maxV)
        {
			if (File.Exists("settings.xml")) {
				File.Delete("settings.xml");
			}
            XmlWriterSettings settings = new XmlWriterSettings();
            settings.Indent = true;

            XmlWriter writer = XmlWriter.Create("settings.xml", settings);
            writer.WriteStartDocument();
            writer.WriteComment("This file is generated by the program.");
            writer.WriteStartElement("Setting");
            writer.WriteAttributeString("Port", port);
            writer.WriteAttributeString("Folder", folder);
            writer.WriteAttributeString("NVersion", maxV);
            writer.WriteEndElement();
            writer.WriteEndDocument();
            writer.Flush();
            writer.Close();
        }

       public String[] readSettings()
        {
            String[] setting= new String[3];
            XmlReader reader = XmlReader.Create("settings.xml");

            while (reader.Read())
            {
                if (reader.NodeType == XmlNodeType.Element && reader.Name == "Setting")
                {
                    setting[0] = reader.GetAttribute(0);
                    setting[1]= reader.GetAttribute(1);
                    setting[2] = reader.GetAttribute(2);
                }
            }
			reader.Close();
            return setting;
        }
    }
}